'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Link from "next/link";
import Image from "next/image";
import { Box } from "@mui/material";
// import theme from "@/component/theme/theme";
import theme from "../component/theme/theme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Trading App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {

 
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AppBar position="static" sx={{bgcolor:theme.palette.btncolor.main}}>
            <Toolbar>
            <Box
                sx={{
                  width: "22px",
                  height: "22px", 
                  borderRadius: "50%", 
                  overflow: "hidden",
                  marginRight: "10px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <Image
                  src="/icon.jpg" 
                  alt="Trading Logo"
                  width={22} 
                  height={22} 
                  style={{ objectFit: "cover" }} 
                />
              </Box>
              <Typography variant="h6" sx={{ flexGrow: 1 }}>
                Trading App
              </Typography>
              <Button color="inherit" disableRipple>
                <Link href="/" passHref>
                  Home
                </Link>
              </Button>
              <Button color="inherit" disableRipple>
                <Link href="/forgotPassword" passHref>
                  Forgot Password
                </Link>
              </Button>
              <Button color="inherit" disableRipple>
                <Link href="/signin" passHref>
                  Sign In
                </Link>
              </Button>
              <Button color="inherit" disableRipple>
                <Link href="/signup" passHref>
                  Sign Up
                </Link>
              </Button>
            </Toolbar>
          </AppBar>
          {/* Main Content */}
          {children}
        </body>
      </html>
    </>
  );
}
